# dispatch명령어 수행해야 action 수행됩니다!!
name: Deploy Spring Boot to Ubuntu Server without Docker Container

on:
  workflow_dispatch: # 수동 실행 트리거
    inputs:
      environment:
        description: "Deployment environment (e.g., staging, production)"
        required: true
        default: "production"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. 코드 체크아웃
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. JDK 설치
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'

    # 3. Gradlew 권한 설정
    - name: Grant execute permission to Gradlew
      run: chmod +x ./gradlew

    # 4. Gradle 빌드
    - name: Build with Gradle
      run: ./gradlew clean build -x test

    # 5. 서버로 JAR 파일 전송
    - name: Transfer JAR to server
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_KEY }}
        source: build/libs/*.jar
        target: /home/${{ secrets.SERVER_USER }}/app/server.jar

    # 6. 서버에서 Spring Boot 실행
    - name: Run Spring Boot on server
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_KEY }}
        script: |
          pkill -f 'java -jar' || true
          nohup java -jar /home/${{ secrets.SERVER_USER }}/app/server.jar > server.log 2>&1 &
